run:
  go: "1.22"
  timeout: 5m
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: readonly
issues:
  exclude:
    - (^|/)fork($|/)
    - pkg/registry/save/lib/
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - gofmt
    - goimports
    - revive
    - stylecheck
    - goconst
    - gosimple
    - misspell
    - whitespace
    - ineffassign
    - typecheck
    - errcheck
    - govet
    - staticcheck
    - unused
    - nilerr
    - unconvert

output:
  # 打印格式：line-number, json, tab, checkstyle, code-climate, junit, gitlab, html
  formats: "line-number"
service:
  # use the fixed version to not introduce new linters unexpectedly
  golangci-lint-version: latest