# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2

project_name: dtools

env:
  - CGO_ENABLED=0
  - GO111MODULE=auto

builds:
  - id: binary
    goos:
      # - freebsd
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=binaryRelease
  - id: snap
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=snap

archives:
  - builds:
      - binary
    name_template: >
      .dtools_{{ .Version }}_{{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.txt
      - README_{{.Os}}.md
      - CHANGELOG.md
      - docs/*

upx:
  - enabled: true
#  compress: best
    compress: 9
    lzma: true
checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Security updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
      order: 400
    - title: 'Build process updates'
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 400
    - title: Other work
      order: 9999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bump"

